network_pkl: &network_pkl
  FFHQ_r1024: "datasets2/pretrained/ffhq-res1024-mirror-stylegan2-noaug.pkl"

loss_cfg: &loss_cfg
  vgg16_conv_r1024_loss_cfg:
    register_modules:
    - exp2.hrinversion.models.vgg_per_loss
    name: exp2.hrinversion.models.vgg_per_loss.VGG16ConvLoss
    model_name: vgg16_conv
    downsample_size: -1
    use_stat_loss: false
    layers:
    - features_2
    - features_7
    - features_14
    - features_21
    - features_28
    loss_w_dict:
      features_2: 0.0002
      features_7: 0.0001
      features_14: 0.0001
      features_21: 0.0002
      features_28: 0.0005


projector_web:
  mode:
    - projector_web
  projector_web:
    image_list_files:
      aligned_faces:
        image_list_file: "datasets2/aligned_faces"
    fps: 20
    loss_cfg: *loss_cfg
    default_loss_cfg: vgg16_conv_r1024_loss_cfg
    num_steps: 1000
    optim_noise_bufs: false
    regularize_noise_weight: 0.0
    initial_learning_rate: 0.1
    proj_w_plus: true
    mse_weight: 50.0
    normalize_noise: true